export const genreReference = {
  asia: "Asia Ethnic",
  bar: "Bar",
  bread: "Bakery",
  cafe: "Cafe",
  chinese: "Chinese",
  curry: "Curry",
  french: "French",
  gyoza: "Gyoza",
  hamburger: "Hamburger",
  ice: "Ice Cream/Gelato",
  italian: "Italian",
  izakaya: "Izakaya",
  japanese: "Japanese",
  kissaten: "Japanese Cafe",
  okonomiyaki: "Okonomiyaki",
  pizza: "Pizza",
  ramen: "Ramen",
  soba: "Soba",
  steak: "Steak",
  sushi: "Sushi",
  dessert: "Dessert",
  teishoku: "Teishoku",
  tempura: "Tempura",
  tonkatsu: "Tonkatsu",
  udon: "Udon",
  unagi: "Unagi",
  wagashi: "Wagashi",
  yakiniku: "Yakiniku",
  yakitori: "Yakitori",
  yoshoku: "Western Japanese",
};

export const genreOptions = [
  { label: "Asia Ethnic", value: "asia" },
  { label: "Bar", value: "bar" },
  { label: "Bakery", value: "bread" },
  { label: "Cafe", value: "cafe" },
  { label: "Chinese", value: "chinese" },
  { label: "Curry", value: "curry" },
  { label: "French", value: "french" },
  { label: "Gyoza", value: "gyoza" },
  { label: "Hamburger", value: "hamburger" },
  { label: "Ice Cream/Gelato", value: "ice" },
  { label: "Italian", value: "italian" },
  { label: "Izakaya", value: "izakaya" },
  { label: "Japanese", value: "japanese" },
  { label: "Japanese Cafe", value: "kissaten" },
  { label: "Okonomiyaki", value: "okonomiyaki" },
  { label: "Pizza", value: "pizza" },
  { label: "Ramen", value: "ramen" },
  { label: "Soba", value: "soba" },
  { label: "Steak", value: "steak" },
  { label: "Sushi", value: "sushi" },
  { label: "Dessert", value: "dessert" },
  { label: "Teishoku", value: "teishoku" },
  { label: "Tempura", value: "tempura" },
  { label: "Tonkatsu", value: "tonkatsu" },
  { label: "Udon", value: "udon" },
  { label: "Unagi", value: "unagi" },
  { label: "Wagashi", value: "wagashi" },
  { label: "Yakiniku", value: "yakiniku" },
  { label: "Yakitori", value: "yakitori" },
  { label: "Western Japanese", value: "yoshoku" },
];

export const prefectureOptions = [
  { label: "北海道 (Hokkaido)", value: "北海道" },
  { label: "青森県 (Aomori)", value: "青森県" },
  { label: "岩手県 (Iwate)", value: "岩手県" },
  { label: "宮城県 (Miyagi)", value: "宮城県" },
  { label: "秋田県 (Akita)", value: "秋田県" },
  { label: "山形県 (Yamagata)", value: "山形県" },
  { label: "福島県 (Fukushima)", value: "福島県" },
  { label: "茨城県 (Ibaraki)", value: "茨城県" },
  { label: "栃木県 (Tochigi)", value: "栃木県" },
  { label: "群馬県 (Gunma)", value: "群馬県" },
  { label: "埼玉県 (Saitama)", value: "埼玉県" },
  { label: "千葉県 (Chiba)", value: "千葉県" },
  { label: "東京都 (Tokyo)", value: "東京都" },
  { label: "神奈川県 (Kanagawa)", value: "神奈川県" },
  { label: "新潟県 (Niigata)", value: "新潟県" },
  { label: "富山県 (Toyama)", value: "富山県" },
  { label: "石川県 (Ishikawa)", value: "石川県" },
  { label: "福井県 (Fukui)", value: "福井県" },
  { label: "山梨県 (Yamanashi)", value: "山梨県" },
  { label: "長野県 (Nagano)", value: "長野県" },
  { label: "岐阜県 (Gifu)", value: "岐阜県" },
  { label: "静岡県 (Shizuoka)", value: "静岡県" },
  { label: "愛知県 (Aichi)", value: "愛知県" },
  { label: "三重県 (Mie)", value: "三重県" },
  { label: "滋賀県 (Shiga)", value: "滋賀県" },
  { label: "京都府 (Kyoto)", value: "京都府" },
  { label: "大阪府 (Osaka)", value: "大阪府" },
  { label: "兵庫県 (Hyogo)", value: "兵庫県" },
  { label: "奈良県 (Nara)", value: "奈良県" },
  { label: "和歌山県 (Wakayama)", value: "和歌山県" },
  { label: "鳥取県 (Tottori)", value: "鳥取県" },
  { label: "島根県 (Shimane)", value: "島根県" },
  { label: "岡山県 (Okayama)", value: "岡山県" },
  { label: "広島県 (Hiroshima)", value: "広島県" },
  { label: "山口県 (Yamaguchi)", value: "山口県" },
  { label: "徳島県 (Tokushima)", value: "徳島県" },
  { label: "香川県 (Kagawa)", value: "香川県" },
  { label: "愛媛県 (Ehime)", value: "愛媛県" },
  { label: "高知県 (Koci)", value: "高知県" },
  { label: "福岡県 (Fukuoka)", value: "福岡県" },
  { label: "佐賀県 (Saga)", value: "佐賀県" },
  { label: "長崎県 (Nagasaki)", value: "長崎県" },
  { label: "熊本県 (Kumamoto)", value: "熊本県" },
  { label: "大分県 (Oita)", value: "大分県" },
  { label: "宮崎県 (Miyazaki)", value: "宮崎県" },
  { label: "鹿児島県 (Kagoshima)", value: "鹿児島県" },
  { label: "沖縄県 (Okinawa)", value: "沖縄県" },
];

export const sortOptions = [
  { label: "Random", value: ["score", "random"] },
  { label: "Ratings Ascending", value: ["score", "ASC"] },
  { label: "Ratings Descending", value: ["score", "DESC"] },
  {
    label: "Lunch Budget Ascending",
    value: ["tabelog_lunch_budget_min", "ASC NULLS LAST"],
  },
  {
    label: "Lunch Budget Descending",
    value: ["tabelog_lunch_budget_max", "DESC NULLS LAST"],
  },
  {
    label: "Dinner Budget Ascending",
    value: ["tabelog_dinner_budget_min", "ASC NULLS LAST"],
  },
  {
    label: "Dinner Budget Descending",
    value: ["tabelog_dinner_budget_max", "DESC NULLS LAST"],
  },
  { label: "Closest Distance", value: ["distance", "ASC NULLS LAST"] },
];
